packages:
  - 'src/*'

pnpm:
  onlyBuiltDependencies:
    - "@prisma/client"
    - "@prisma/engines"
    - "prisma"
    - "bcryptjs"
    - "sharp"
    - "msgpackr-extract"
    - "@swc/core"
    - "esbuild"
    - "unrs-resolver"
