"use server";

import { db } from "@/lib/db/json-db";

const SYSTEM_PROMPT = `You are a Senior Software Architect, Staff Engineer, UI/UX Designer, DevOps Engineer, Security Expert and QA Engineer combined.
Rules:
- Never generate partial code.
- Always generate production-ready code.
- Always create complete project structure.
- Generate every required file.
- Write full implementation, never use placeholders.
- Maintain clean architecture and scalable design patterns.
- Follow industry best practices.
- Add comments where necessary.
- Handle all edge cases.
- Include security, validation, error handling and logging.
- Generate responsive and modern UI.
- Use latest stable technologies.
- Maintain modular codebase.
- Optimize performance and database queries.
- Create reusable components.
- Generate deployment configuration.
- Generate environment variables setup.
- Generate API documentation.
- Generate database schema and migrations.
- Generate admin panel if required.
- Generate testing files.`;

export async function generateCode(prompt: string, framework: string) {
  console.log(`[AI Persona Active] Generating elite code for: ${prompt} using ${framework}`);

  // Simulate complex generation delay
  await new Promise(resolve => setTimeout(resolve, 3500));

  const lowerPrompt = prompt.toLowerCase();

  if (framework === 'nextjs') {
    return [
      {
        name: "src/app/page.tsx",
        language: "typescript",
        content: `"use client";
import { motion } from "framer-motion";
import { Sparkles, Zap, Shield, Rocket } from "lucide-react";

export default function Home() {
  return (
    <div className="min-h-screen bg-black text-white font-sans selection:bg-white selection:text-black">
      <nav className="border-b border-white/10 px-8 py-4 flex justify-between items-center backdrop-blur-md sticky top-0 z-50">
        <div className="text-xl font-black tracking-tighter">ELITE.STUDIO</div>
        <div className="flex gap-6 text-sm font-medium text-neutral-400">
          <a href="#" className="hover:text-white transition-colors">Features</a>
          <a href="#" className="hover:text-white transition-colors">Pricing</a>
          <a href="#" className="hover:text-white transition-colors">Docs</a>
        </div>
        <button className="bg-white text-black px-4 py-1.5 rounded-full text-sm font-bold hover:bg-neutral-200 transition-all">
          Get Started
        </button>
      </nav>

      <main className="max-w-6xl mx-auto px-8 pt-32 pb-20 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <h1 className="text-7xl md:text-9xl font-black tracking-tightest leading-none mb-8">
            CRAFTED WITH <span className="text-neutral-500 italic">PRECISION</span>
          </h1>
          <p className="text-xl text-neutral-400 max-w-2xl mx-auto mb-12 leading-relaxed">
            A high-performance boilerplate generated by Elite AI. Built for speed, scale, and uncompromising quality.
          </p>
          <div className="flex gap-4 justify-center">
            <button className="bg-white text-black px-8 py-4 rounded-xl font-bold text-lg hover:scale-105 transition-transform">
              Deploy Project
            </button>
            <button className="border border-white/20 px-8 py-4 rounded-xl font-bold text-lg hover:bg-white/5 transition-colors">
              View Source
            </button>
          </div>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-40">
          {[
            { icon: Zap, title: "Ultra Fast", desc: "Optimized for sub-second page loads and interaction." },
            { icon: Shield, title: "Secure", desc: "Enterprise-grade security protocols baked into the core." },
            { icon: Rocket, title: "Scalable", desc: "Modular architecture that grows with your user base." }
          ].map((item, i) => (
            <div key={i} className="p-8 rounded-3xl border border-white/5 bg-neutral-900/50 text-left hover:border-white/20 transition-colors group">
              <item.icon className="w-8 h-8 mb-6 text-neutral-500 group-hover:text-white transition-colors" />
              <h3 className="text-xl font-bold mb-2">{item.title}</h3>
              <p className="text-neutral-500 leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}`
      },
      {
        name: "src/app/layout.tsx",
        language: "typescript",
        content: `import './globals.css';\nimport { Inter } from 'next/font/google';\n\nconst inter = Inter({ subsets: ['latin'] });\n\nexport const metadata = {\n  title: 'Elite Generated App',\n  description: 'Built with Elite AI',\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body className={inter.className}>{children}</body>\n    </html>\n  );\n}`
      },
      {
        name: "next.config.js",
        language: "javascript",
        content: `/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  reactStrictMode: true,\n};\n\nmodule.exports = nextConfig;`
      }
    ];
  }

  if (framework === 'node') {
    return [
      {
        name: "src/server.ts",
        language: "typescript",
        content: `import express, { Request, Response } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(helmet());
app.use(cors());
app.use(express.json());

// Health check
app.get('/health', (req: Request, res: Response) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString() });
});

// Mock API Route
app.get('/api/v1/data', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: [
      { id: 1, name: 'Professional Node.js API' },
      { id: 2, name: 'Built with Elite AI' }
    ]
  });
});

app.listen(PORT, () => {
  console.log(\`[Server] Running on http://localhost:\${PORT}\`);
});`
      },
      {
        name: "package.json",
        language: "json",
        content: `{\n  "name": "elite-node-api",\n  "version": "1.0.0",\n  "main": "dist/server.js",\n  "scripts": {\n    "start": "node dist/server.js",\n    "dev": "ts-node-dev src/server.ts",\n    "build": "tsc"\n  },\n  "dependencies": {\n    "express": "^4.18.2",\n    "cors": "^2.8.5",\n    "helmet": "^7.0.0",\n    "dotenv": "^16.3.1"\n  },\n  "devDependencies": {\n    "@types/express": "^4.17.17",\n    "@types/node": "^20.5.0",\n    "typescript": "^5.1.6",\n    "ts-node-dev": "^2.0.0"\n  }\n}`
      },
      {
        name: "tsconfig.json",
        language: "json",
        content: `{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "commonjs",\n    "outDir": "./dist",\n    "rootDir": "./src",\n    "strict": true,\n    "esModuleInterop": true,\n    "skipLibCheck": true,\n    "forceConsistentCasingInFileNames": true\n  }\n}`
      }
    ];
  }

  // Fallback for others
  return [
    {
      name: "README.md",
      language: "markdown",
      content: `# Elite Generated Project\n\nGenerated for: ${prompt}\nFramework: ${framework}\n\n## Getting Started\n\n1. Install dependencies: \`npm install\`\n2. Start development: \`npm run dev\`\n3. Build for production: \`npm run build\``
    },
    {
      name: "main.py",
      language: "python",
      content: `from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/")\ndef read_root():\n    return {"Hello": "Elite Developer", "Prompt": "${prompt}"}`
    }
  ];
}

export async function diagnoseCode(code: string) {
  // Simulate AI code diagnosis
  await new Promise(resolve => setTimeout(resolve, 1500));

  const issues = [];
  if (!code.includes("import")) {
    issues.push("Missing imports for external dependencies.");
  }
  if (code.includes("any") && !code.includes("React.ReactNode")) {
    issues.push("Type 'any' used. Consider using specific types for better safety.");
  }
  if (issues.length === 0) {
    return { status: "clean", message: "No critical errors detected. Code is elite." };
  }
  return { status: "issues", message: "Found potential issues:", details: issues };
}
